version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "httptest"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-n3gnyvou5meu"
s3_prefix = "httptest"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"

