AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  http-test

  Sample SAM Template for http-test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Handler: index.lambda_handler
    Runtime: python3.7
    Timeout: 3

Resources:
  Api:
    Type: AWS::Serverless::HttpApi

  ReadTitles:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/read_titles
      Events:
        GetAllSoftware:
          Type: HttpApi
          Properties:
            Path: /v1/{contributor_id}/software
            Method: get
            ApiId: !Ref Api
        GetSelectSoftware:
          Type: HttpApi
          Properties:
            Path: /v1/{contributor_id}/software/{title_ids}
            Method: get
            ApiId: !Ref Api
        GetPatch:
          Type: HttpApi
          Properties:
            Path: /v1/{contributor_id}/patch/{title_id}
            Method: get
            ApiId: !Ref Api

