AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  http-test

  Sample SAM Template for http-test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Handler: index.lambda_handler
    Runtime: python3.7
    Timeout: 3

Resources:
  Api:
    Type: AWS::Serverless::HttpApi
  GetSoftware:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/get_software
      Events:
        GetAllSoftware:
          Type: HttpApi
          Properties:
            Path: /v1/{contributor}/software
            Method: get
            ApiId: !Ref Api
        GetSelectSoftware:
          Type: HttpApi
          Properties:
            Path: /v1/{contributor}/software/{titles}
            Method: get
            ApiId: !Ref Api
  GetPatch:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/get_patch
      Events:
        GetPatch:
          Type: HttpApi
          Properties:
            Path: /v1/{contributor}/patch/{title}
            Method: get
            ApiId: !Ref Api